'use strict';
let config,player,playing=false,index=0,started=performance.now();
const $=id=>document.getElementById(id),art=$('art'),base=$('base');
function showError(message){$('error').textContent=message;$('error').hidden=false}
function place(el,r){el.style.left=r[0]*100+'%';el.style.top=r[1]*100+'%';el.style.width=r[2]*100+'%';el.style.height=r[3]*100+'%'}
function fit(){if(!config||config.kind==='effect')return;const extra=config.kind==='cd'&&config.youtube?224:0,w=innerWidth,h=Math.max(1,innerHeight-extra),scale=Math.min(w/config.width,h/config.height);art.style.width=config.width*scale+'px';art.style.height=config.height*scale+'px'}
function playback(value){playing=value;$('disc').style.animationPlayState=value?'running':'paused';$('play').textContent=value?'Ⅱ':'▶';$('play').setAttribute('aria-label',value?'일시정지':'재생')}
function toggle(){if(player&&typeof player.getPlayerState==='function'){player.getPlayerState()===1?player.pauseVideo():player.playVideo()}else if(!config.youtube)playback(!playing)}
function next(){index=(index+1)%config.images.length;base.src=config.images[index];started=performance.now()}
function storyTick(now){if(now-started>=3600)next();[...$('bars').children].forEach((bar,i)=>bar.firstChild.style.transform='scaleX('+(i<index?1:i===index?Math.max(0,Math.min(1,(now-started)/3600)):0)+')');requestAnimationFrame(storyTick)}
window.onYouTubeIframeAPIReady=()=>{player=new YT.Player('youtube',{width:356,height:200,videoId:config.youtube,playerVars:{autoplay:1,playsinline:1,origin:location.origin,rel:0},events:{onReady:e=>{e.target.playVideo();$('message').textContent='자동재생이 시작되지 않으면 ▶를 눌러 주세요.'},onStateChange:e=>{playback(e.data===1);$('message').textContent=e.data===1?'재생 중 · 앨범 버튼으로 일시정지':'앨범 버튼으로 이어서 재생'},onAutoplayBlocked:()=>{playback(false);$('message').textContent='유튜브 ▶를 눌러 재생해 주세요.'},onError:e=>{playback(false);$('message').textContent='이 영상은 외부에서 재생할 수 없습니다. ('+e.data+')'}}})};
async function start(){try{const response=await fetch('config.json');if(!response.ok)throw Error('위젯 설정을 불러오지 못했습니다.');config=await response.json();document.title=(config.title||'Memory Studio')+' · 위젯';
if(config.kind==='effect'){art.hidden=true;const params=new URLSearchParams(config.effect);params.set('img',new URL(config.images[0],location.href).href);if(config.images[1]&&!params.get('img2'))params.set('img2',new URL(config.images[1],location.href).href);$('effect').src='effects.html?'+params.toString();$('effect').hidden=false;return}
base.src=config.images[0];base.onerror=()=>showError('사진을 불러오지 못했습니다. 잠시 후 새로고침해 주세요.');fit();addEventListener('resize',fit);
if(config.kind==='story'){const bars=$('bars');bars.hidden=false;bars.style.top=24/config.designHeight*100+'%';bars.style.height=4/config.designHeight*100+'%';for(const image of config.images){const s=document.createElement('span');s.appendChild(document.createElement('i'));bars.appendChild(s)}art.tabIndex=0;art.setAttribute('role','button');art.setAttribute('aria-label','다음 사진');art.style.cursor='pointer';art.addEventListener('click',next);art.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();next()}});requestAnimationFrame(storyTick)}
if(config.kind==='tilt'){art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),i=Math.max(0,Math.min(config.images.length-1,Math.round((e.clientX-r.left)/r.width*(config.images.length-1))));base.src=config.images[i]});art.addEventListener('pointerleave',()=>base.src=config.images[Math.floor(config.images.length/2)]);base.src=config.images[Math.floor(config.images.length/2)]}
if(config.kind==='camera'){art.style.cursor='pointer';art.addEventListener('click',()=>{base.src=config.images[0]+'?replay='+Date.now()})}
if(config.kind==='cd'){const disc=$('disc'),sleeve=$('sleeve'),button=$('play');disc.src='disc.png';sleeve.src='sleeve.png';disc.hidden=sleeve.hidden=button.hidden=false;place(disc,config.disc);place(sleeve,config.sleeve);place(button,config.button);button.addEventListener('click',toggle);if(config.youtube){$('video').hidden=false;fit();const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.onerror=()=>showError('유튜브를 불러오지 못했습니다.');document.head.appendChild(script)}else playback(true)}
}catch(e){showError(e.message)}}start();
