'use strict';
const $=id=>document.getElementById(id),definitions=[['scratch','🪙 복권 긁기'],['frost','❄ 성에 닦기'],['dust','🧽 먼지 닦기'],['camera','📷 카메라'],['polaroid','🖼 폴라로이드'],['film','🎞 필름 감기'],['gift','🎁 선물상자'],['gacha','🥚 캡슐토이'],['parcel','📦 택배 개봉'],['envelope','💌 편지 봉투'],['curtain','🎭 커튼'],['blind','🪟 블라인드'],['blackout','🌑 암막 스와이프'],['unlock','🔓 밀어서 열기'],['origami','📄 종이접기'],['snowglobe','🔮 스노우볼'],['slot','🎰 슬롯머신'],['holo','🌈 홀로그램'],['scan','📡 스캔'],['cd','💿 CD 앨범']];
let effect='scratch',timer;const sample='../w/f1397a4e10d04cd082a432a10ec8f9aa/frame-0.png';
$('runtime').value=new URL('effects.html',location.href).href;$('albumRuntime').value=new URL('album.html',location.href).href;$('img').value=new URL(sample,location.href).href;
const escapeAttribute=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function https(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u:null}catch{return null}}
function update(){clearTimeout(timer);$('music').hidden=effect!=='cd';for(const b of $('effects').children)b.setAttribute('aria-pressed',b.dataset.effect===effect?'true':'false');const base=$(effect==='cd'?'albumRuntime':'runtime').value.trim(),u=https(base);let error='';if(!u)error='실행 주소에 올바른 HTTPS URL을 입력하세요.';for(const k of ['img','img2','cover'])if(($(k).value.trim()||k==='img')&&!https($(k).value.trim()))error='공개 이미지의 HTTPS 주소를 확인하세요.';if(error){$('url').value=$('embed').value='';$('status').textContent=error;for(const id of ['copyUrl','copyEmbed','open','check'])$(id).disabled=true;return}for(const id of ['copyUrl','copyEmbed','open','check'])$(id).disabled=false;u.search='';u.hash='';u.searchParams.set('fx',effect);for(const k of ['img','img2','cover','title','sub','label','ratio','fit','accent','radius','pct','blur'])if($(k).value.trim())u.searchParams.set(k,$(k).value.trim());if($('auto').checked)u.searchParams.set('auto','1');if(effect==='cd'){u.searchParams.set('yt',$('yt').value.trim());u.searchParams.set('portrait',['2/3','3/4'].includes($('ratio').value)?'1':'0')}
const url=u.href;const width=Math.min(2000,Math.max(200,Number($('width').value)||1000));const [rw,rh]=$('box').value.split('/').map(Number);const height=Math.round(width*rh/rw);
$('url').value=url;$('embed').value='<div style="width:'+width+'px;max-width:100%;margin:0 auto 1rem;position:relative;aspect-ratio:'+rw+'/'+rh+';">\n  <iframe src="'+escapeAttribute(url)+'" width="100%" height="'+height+'" scrolling="auto" frameborder="0"\n    style="width:100%;height:100%;border:0;display:block"\n    allow="autoplay; encrypted-media; accelerometer; gyroscope; picture-in-picture"></iframe>\n</div>';
$('compatibility').textContent=['nyayna.github.io','straker.pages.dev'].includes(u.hostname)?'이 실행 사이트 주소는 숲 비교 테스트에서 거부되었습니다. 코드 복사는 가능하지만, 숲에서 작동하려면 실행 주소의 허용이 필요합니다.':'이 실행 주소의 숲 호환성은 확인되지 않았습니다. 숲 검사 응답과 테스트 게시판 미리보기로 확인하세요.';
$('status').textContent='미리보기와 코드가 갱신되었습니다.';if($('preview').src!==url)$('preview').src=url;}
for(const [id,name]of definitions){const b=document.createElement('button');b.type='button';b.dataset.effect=id;b.textContent=name;b.onclick=()=>{effect=id;update()};$('effects').appendChild(b)}
for(const input of document.querySelectorAll('input,select'))input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(update,350)});
async function copy(id){try{await navigator.clipboard.writeText($(id).value);$('status').textContent='복사했습니다.'}catch{$(id).focus();$(id).select();$('status').textContent='Ctrl+C로 선택된 내용을 복사하세요.'}}
$('copyUrl').onclick=()=>copy('url');$('copyEmbed').onclick=()=>copy('embed');$('open').onclick=()=>window.open($('url').value,'_blank','noopener');$('check').onclick=()=>window.open('https://api-channel.sooplive.com/v1.1/channel/oembed?url='+encodeURIComponent($('url').value),'_blank','noopener');$('replay').onclick=()=>{$('preview').src=$('url').value};update();
